# Generated by Django 4.2.30 on 2026-07-29 10:55

from django.db import migrations, models
import tallyapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_company', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logo/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='signature/')),
                ('comp_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_address', models.CharField(blank=True, max_length=500, null=True)),
                ('comp_state', models.CharField(blank=True, max_length=40, null=True)),
                ('comp_website', models.CharField(blank=True, max_length=40, null=True)),
                ('comp_gstin', models.CharField(blank=True, max_length=40, null=True)),
                ('comp_guid', models.CharField(blank=True, default='', max_length=40)),
                ('comp_starting_from', models.DateField(blank=True, null=True)),
                ('vat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('next_15_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Active Date')),
                ('renew_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('gstamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('module_type', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('modules1', models.JSONField(blank=True, default=tallyapp.models.default_specific_workouts, null=True)),
                ('premium_modules', models.JSONField(blank=True, default=list, null=True)),
                ('remain_invoice', models.IntegerField(blank=True, default=0, null=True)),
                ('udyam', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('state_code', models.IntegerField(blank=True, default=0, null=True)),
                ('platform', models.CharField(blank=True, max_length=10, null=True)),
                ('e_invoice', models.BooleanField(default=False)),
                ('portal_email', models.CharField(blank=True, max_length=70, null=True)),
                ('portal_password', models.CharField(blank=True, max_length=50, null=True)),
                ('e_way_bill', models.BooleanField(default=False)),
                ('e_way_bill_portal_username', models.CharField(blank=True, max_length=70, null=True)),
                ('e_way_bill_portal_password', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_username', models.CharField(blank=True, max_length=20, null=True)),
                ('inventory', models.BooleanField(blank=True, default=None, null=True)),
                ('auto_increment', models.BooleanField(blank=True, default=False, null=True)),
                ('round_off', models.BooleanField(blank=True, default=True, null=True)),
                ('payment_QR', models.ImageField(blank=True, max_length=300, null=True, upload_to='pay_QR/')),
                ('fifo_lifo', models.CharField(choices=[('FIFO', 'First In First Out'), ('LIFO', 'Last In First Out')], default='FIFO', max_length=10)),
                ('is_voucher_qr', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
