# Generated by Django 4.2.30 on 2026-07-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=400, null=True)),
                ('under_group', models.CharField(blank=True, max_length=101, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('ledgergroup_guid', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companydata')),
            ],
        ),
        migrations.CreateModel(
            name='ladgernamedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledeger_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('ledeger_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ledeger_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ledeger_address', models.CharField(blank=True, max_length=300, null=True)),
                ('ledeger_state', models.CharField(blank=True, max_length=50, null=True)),
                ('ledger_pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('ledeger_guid', models.CharField(blank=True, default='', max_length=51)),
                ('ledeger_website', models.CharField(blank=True, max_length=49, null=True)),
                ('ledeger_gstin', models.CharField(blank=True, max_length=25, null=True)),
                ('ledger_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger_ifsc', models.CharField(blank=True, max_length=31, null=True)),
                ('ledger_accno', models.CharField(blank=True, max_length=50, null=True)),
                ('ledger_sac', models.CharField(blank=True, max_length=30, null=True)),
                ('gst_rate', models.CharField(blank=True, max_length=8, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.IntegerField(blank=True, default=0, null=True)),
                ('platform', models.CharField(blank=True, max_length=9, null=True)),
                ('ledger_gst_reg_type', models.CharField(blank=True, max_length=25, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companydata')),
                ('ledeger_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.grouplist')),
            ],
            options={
                'verbose_name_plural': 'Tally Ledgers (ladgernamedata)',
            },
        ),
    ]
