# Generated by Django 4.2.30 on 2026-07-29 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=60, null=True)),
                ('rec_data', models.JSONField(blank=True, default=dict, null=True)),
                ('pay_data', models.JSONField(blank=True, default=dict, null=True)),
                ('credit_note_data', models.JSONField(blank=True, default=dict, null=True)),
                ('debit_note_data', models.JSONField(blank=True, default=dict, null=True)),
                ('received', models.JSONField(blank=True, default=dict, null=True)),
                ('paid', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('partial_paid', models.JSONField(blank=True, default=dict, null=True)),
                ('partial_received', models.JSONField(blank=True, default=dict, null=True)),
                ('openingBalance', models.JSONField(blank=True, default=list, null=True)),
                ('max_voucher_no', models.CharField(default=0, max_length=20)),
                ('bank_entry_data', models.JSONField(blank=True, default=dict, null=True)),
                ('distribution_entry_data', models.JSONField(blank=True, default=dict, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companydata')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recpay',
            constraint=models.UniqueConstraint(fields=('user_email', 'company'), name='unique_user_company'),
        ),
    ]
