# Generated by Django 4.2.30 on 2026-07-29 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0002_grouplist_ladgernamedata'),
        ('celery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ledger_json', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companydata')),
            ],
        ),
    ]
