# Generated by Django 4.2.30 on 2026-07-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0002_ledgerexport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LedgerExport',
        ),
    ]
