# Generated by Django 4.2.30 on 2026-07-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opening_balance_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal'), ('debit_note', 'Debit Note'), ('credit_note', 'Credit Note')], default='journal', max_length=20)),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nature', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.ledgergroup')),
            ],
            options={
                'verbose_name': 'Ledger group',
                'verbose_name_plural': 'Ledger groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.voucher')),
            ],
            options={
                'verbose_name': 'Ledger entry',
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='ledger.ledgergroup'),
        ),
    ]
