# Generated by Django 4.2.30 on 2026-07-09 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_movement_date', models.DateField(blank=True, null=True)),
                ('preferred_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_stock_items', to='ledger.ledger')),
            ],
            options={
                'verbose_name': 'Stock item',
                'verbose_name_plural': 'Stock items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(blank=True, max_length=50, verbose_name='So number')),
                ('order_date', models.DateField()),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('order_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_dispatched', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='ledger.ledger')),
            ],
            options={
                'verbose_name': 'Sales order',
                'verbose_name_plural': 'Sales orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=50, verbose_name='Po number')),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_received', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='ledger.ledger')),
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
    ]
