# Generated by Django 4.2.30 on 2026-07-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_stockitem_salesorder_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_movement_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('fabric_type', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('pattern', models.CharField(blank=True, max_length=50)),
                ('quality', models.CharField(blank=True, max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='ledger.stockitem')),
            ],
            options={
                'verbose_name': 'Stock SKU',
                'verbose_name_plural': 'Stock SKUs',
                'ordering': ['sku_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='stocksku',
            constraint=models.UniqueConstraint(fields=('item', 'sku_code'), name='uniq_item_sku'),
        ),
    ]
