# Generated by Django 4.2.30 on 2026-07-30 12:36

from django.db import migrations, models
import django.db.models.deletion
import inventory_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tallyapp', '0002_grouplist_ladgernamedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('Group', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.JSONField(blank=True, default=list, null=True)),
                ('other_details', models.JSONField(blank=True, default=list, null=True)),
                ('vendor', models.JSONField(blank=True, default=list, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('raw_reference', models.JSONField(blank=True, default=list, null=True)),
                ('semi_finished_reference', models.JSONField(blank=True, default=list, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('Group', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.JSONField(blank=True, default=list, null=True)),
                ('other_details', models.JSONField(blank=True, default=list, null=True)),
                ('vendor', models.JSONField(blank=True, default=list, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('raw_reference', models.JSONField(blank=True, default=list, null=True)),
                ('semi_finished_reference', models.JSONField(blank=True, default=list, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('warehouse_address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_manufacturing_plant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('other_details', models.JSONField(blank=True, default=list, null=True)),
                ('sku_pattern', models.JSONField(blank=True, default=inventory_management.models.default_sku_pattern, null=True)),
                ('sku_code', models.JSONField(blank=True, default=list, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=30, null=True)),
                ('pdf_format', models.CharField(blank=True, max_length=6, null=True)),
                ('deadStock', models.IntegerField(blank=True, null=True)),
                ('businessType', models.CharField(blank=True, max_length=30, null=True)),
                ('description_pattern', models.JSONField(blank=True, default=list, null=True)),
                ('fifo_lifo', models.CharField(choices=[('FIFO', 'First In First Out'), ('FEFO', 'First Expiry First Out'), ('LIFO', 'Last In First Out')], default='FIFO', max_length=10)),
                ('expiry_alert_days', models.PositiveIntegerField(default=0, help_text='Show products expiring within these many days')),
                ('is_negative', models.BooleanField(default=False)),
                ('barcode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companydata')),
            ],
        ),
    ]
