# Generated by Django 4.2.30 on 2026-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycredentials',
            name='monthly_stock_snapshot',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
