# Generated by Django 4.2.30 on 2026-08-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_companycredentials_monthly_stock_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycredentials',
            name='user',
            field=models.IntegerField(blank=True, db_column='user_id', null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='user',
            field=models.IntegerField(blank=True, db_column='user_id', null=True),
        ),
    ]
