# Generated by Django 4.2.30 on 2026-07-30 04:45

from django.db import migrations, models
import django.db.models.deletion
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_data', models.CharField(blank=True, max_length=100, null=True)),
                ('Buyer_data', models.JSONField(default=dict)),
                ('Bank', models.CharField(blank=True, max_length=100, null=True)),
                ('Invoice_no', models.CharField(blank=True, max_length=20, null=True)),
                ('Invoice_date', models.DateField(blank=True, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=25, null=True)),
                ('doc_no', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('doc_PDF', models.FileField(blank=True, max_length=600, null=True, upload_to='docInvoicePdf/')),
                ('CA_email', models.CharField(blank=True, max_length=50, null=True)),
                ('Invoice_PDF', models.FileField(blank=True, max_length=600, null=True, upload_to='invoicepdf/')),
                ('ewayBill_PDF', models.FileField(blank=True, max_length=600, null=True, upload_to='ewaybillpdf/')),
                ('payment_QR', models.ImageField(blank=True, max_length=300, null=True, upload_to='payment_QR/')),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('Invoice_type', models.CharField(blank=True, max_length=10, null=True)),
                ('x_deleted', models.BooleanField(default=False)),
                ('y_deleted', models.BooleanField(default=False)),
                ('upload_type', models.CharField(blank=True, max_length=30, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=50, null=True)),
                ('IRN', models.CharField(blank=True, max_length=100, null=True)),
                ('IRN_Date', models.DateField(blank=True, null=True)),
                ('ack_no', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_code/')),
                ('Eway_bill_date', models.DateField(blank=True, null=True)),
                ('ewayBill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('gstr1_ack_no', models.CharField(blank=True, max_length=25, null=True)),
                ('Total', models.FloatField(blank=True, default=0.0, null=True)),
                ('response_json', models.JSONField(blank=True, default=invoice.models.get_empty_response_json, null=True)),
                ('reference_from', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('past_tally_invoice', models.BooleanField(default=False)),
                ('uploaded_file', models.BooleanField(default=False)),
                ('sameAsSeller', models.BooleanField(default=True)),
                ('sameAsBuyer', models.BooleanField(default=True)),
                ('alankit_payload', models.JSONField(blank=True, default=invoice.models.get_empty_payload, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_data', models.CharField(blank=True, max_length=100, null=True)),
                ('Buyer_data', models.CharField(blank=True, max_length=100, null=True)),
                ('Products', models.TextField(blank=True, null=True)),
                ('Invoice_type', models.CharField(blank=True, max_length=10, null=True)),
                ('Description', models.TextField(blank=True, max_length=500, null=True)),
                ('remain_qty', models.FloatField(blank=True, default=0.0, null=True)),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('Discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('Amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('CGST', models.FloatField(blank=True, default=0.0, null=True)),
                ('SGST', models.FloatField(blank=True, default=0.0, null=True)),
                ('IGST', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_cgst_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_sgst_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_igst_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=25, null=True)),
                ('Hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('Rate', models.CharField(blank=True, max_length=20, null=True)),
                ('Per', models.CharField(blank=True, max_length=40, null=True)),
                ('platform', models.CharField(blank=True, max_length=5, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
                ('past_tally_invoice', models.BooleanField(default=False)),
                ('matching', models.CharField(blank=True, max_length=10, null=True)),
                ('warehouse', models.JSONField(blank=True, default=list, null=True)),
                ('so_remove_qty', models.JSONField(blank=True, default=list, null=True)),
                ('ref_doc_no', models.CharField(blank=True, max_length=20, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_details', models.JSONField(blank=True, default=dict, null=True)),
                ('Invoice_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
